--[[
    JULES-CORE FINAL BUILDER (VXload Pro)
    Created for Putra Spa Flexo E

    This script will generate a HIGHLY OBFUSCATED loader.
    - Hidden gg.makeRequest
    - Hidden load/pcall
    - Multi-stage XOR
    - Automatic file generation
]]

-- Configuration
local DEFAULT_FILE = "VXLOAD_PROTECTED.lua"

-- Function to generate obfuscated string from byte codes
local function to_bytes_str(str)
    local out = ""
    for i = 1, #str do
        out = out .. "\\" .. string.byte(str, i)
    end
    return out
end

-- XOR Encryption
local function encrypt(str, k)
    local out = {}
    for i = 1, #str do
        local b = string.byte(str, i)
        local kb = string.byte(k, (i - 1) % #k + 1)
        table.insert(out, string.format("%02X", b ~ kb))
    end
    return table.concat(out)
end

-- THE BUILDER LOGIC
local function build()
    local prompt = gg.prompt({"Input Raw Script URL:", "Output Filename:"}, {"", DEFAULT_FILE}, {"text", "text"})

    if not prompt then return end
    local url = prompt[1]
    local filename = prompt[2]

    if url == "" then
        gg.alert("❌ Error: URL cannot be empty!")
        return
    end

    local key = "JULES-PRO-ENCRYPT-" .. os.time() -- Dynamic key
    local encrypted_hex = encrypt(url, key)

    -- Obfuscated code parts
    -- We use byte sequences to hide everything
    local str_gg = to_bytes_str("gg")
    local str_makeRequest = to_bytes_str("makeRequest")
    local str_load = to_bytes_str("load")
    local str_pcall = to_bytes_str("pcall")
    local str_content = to_bytes_str("content")
    local str_code = to_bytes_str("code")
    local str_tonumber = to_bytes_str("tonumber")
    local str_sub = to_bytes_str("sub")

    -- The Loader Template
    local template = [[
-- Generated by JULES-CORE (VXload Pro)
local _G = _G
local _s = string
local _c = _s.char
local _b = _s.byte
local _t = _G[']] .. str_tonumber .. [[']
local _k = "]] .. key .. [["
local _h = "]] .. encrypted_hex .. [["

local function _v(_x)
    local _u = ""
    local _sb = _s[']] .. str_sub .. [[']
    for i = 1, #_x, 2 do
        local _bv = _t(_sb(_x, i, i + 1), 16)
        local _kv = _b(_k, ((i / 2 - 0.5) % #_k) + 1)
        _u = _u .. _c(_bv ~ _kv)
    end
    return _u
end

local _g = _G[']] .. str_gg .. [[']
local _mr = _g[']] .. str_makeRequest .. [[']
local _ld = _G[']] .. str_load .. [[']
local _pc = _G[']] .. str_pcall .. [[']

local _res = _mr(_v(_h))
if _res and _res[']] .. str_code .. [['] == 200 then
    local _f, _e = _ld(_res[']] .. str_content .. [['])
    if _f then
        _pc(_f)
    else
        _g.alert("Execution Failed")
    end
else
    _g.toast("Connection Error")
end
]]

    -- Writing to file
    local file, err = io.open(filename, "w")
    if file then
        file:write(template)
        file:close()
        gg.alert("✅ SUCCESS!\nFile saved as: " .. filename .. "\n\nLink script Anda sekarang aman dan terenkripsi.")
    else
        gg.alert("❌ FAILED to write file: " .. tostring(err))
    end
end

-- RUN BUILDER
if gg then
    build()
else
    print("This script must be run in Game Guardian.")
end
