--[[
    VXLOAD ULTIMATE BUILDER (JULES-CORE)
    Professional Protection for Online GG Scripts.
]]

local function encrypt(data, key)
    local out = {}
    local prev = 42
    for i = 1, #data do
        local b = data:byte(i)
        local k = key:byte((i-1) % #key + 1)
        local enc = (b ~ k ~ prev) % 256
        table.insert(out, string.format("%02X", enc))
        prev = enc
    end
    return table.concat(out)
end

local function build()
    local p = gg.prompt({"Paste Raw URL:", "File Name:"}, {"", "PROTECTED_SCRIPT.lua"}, {"text", "text"})
    if not p or p[1] == "" then return end

    local url = p[1]
    local filename = p[2]
    local key = "K-" .. math.random(1000, 9999) .. os.time()
    local hex = encrypt(url, key)

    -- Helper to create a math-obfuscated string
    local function hide_str(s)
        local codes = {}
        local seed = math.random(10, 50)
        for i = 1, #s do
            table.insert(codes, s:byte(i) + seed)
        end
        return "((function(...) local r='' local a={...} for i=2,#a do r=r..string.char(a[i]-a[1]) end return r end)(" .. seed .. "," .. table.concat(codes, ",") .. "))"
    end

    local loader_code = [[
local _G = _G
local _c = string.char
local _b = string.byte
local _m = math
local _t = tonumber

-- Hidden Keys
local _S1 = ]] .. hide_str("gg") .. [[
local _S2 = ]] .. hide_str("makeRequest")
.. "\nlocal _S3 = " .. hide_str("load")
.. "\nlocal _S4 = " .. hide_str("pcall")
.. "\nlocal _S5 = " .. hide_str("content")
.. "\nlocal _S6 = " .. hide_str("code")
.. "\nlocal _S7 = " .. hide_str("sub") .. [[

local _K = ]] .. hide_str(key) .. [[
local _H = "]] .. hex .. [["

local function _D(_h)
    local _u = ""
    local _p = 42
    local _sb = string[_S7]
    for i = 1, #_h, 2 do
        local _ev = _t(_sb(_h, i, i+1), 16)
        local _kv = _b(_K, ((i/2-0.5) % #_K) + 1)
        local _dv = (_ev ~ _kv ~ _p) % 256
        _u = _u .. _c(_dv)
        _p = _ev
    end
    return _u
end

local _GG = _G[_S1]
local _REQ = _GG[_S2]
local _LOAD = _G[_S3]
local _PC = _G[_S4]

local function _MAIN()
    local _URL = _D(_H)
    local _RES = _REQ(_URL)
    if _RES and _RES[_S6] == 200 then
        local _F, _E = _LOAD(_RES[_S5])
        if _F then
            _PC(_F)
        else
            _GG.alert("Error: 101")
        end
    else
        _GG.toast("Error: 404")
    end
end

_PC(_MAIN)
]]

    local f = io.open(filename, "w")
    if f then
        f:write("-- Generated by VXLOAD Ultimate\n" .. loader_code)
        f:close()
        gg.alert("✅ PROTECTED!\nFile: " .. filename)
    else
        gg.alert("❌ Write Error")
    end
end

if gg then build() else print("Run in GG") end
